### ISSUE TITLE
Better calendar navigation

### ISSUE THREAD

**Issue by aleeraser** [Maldus512/wt32-sc01-clock#8]
Tapping on a specific day in the calendar opens a detailed view for that day, but when navigating back from that detailed view, the calendar shows the current month instead of the month of the date that was originally tapped.

e.g. if a user taps on a date 5 months from now, navigating back from the date's detailed view should navigate back to the original month view, not defaulting to the current view.

**Comment by Maldus512** [comment]
Fixed by 8135ad393ac45083cfa9f141c7a2229427bb1549
